language: node_js
node_js:
  - node
  - iojs
  - 6
  - 4
  - 0.12
before_install:
  - "npm install grunt-cli -g"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_ENC_API_KEY
  on:
    tags: true
